//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package share.msg.CES010Msg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for MainBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MainBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgId" type="{}MsgId"/>
 *         &lt;element name="OrgnlMsgId" type="{}OrgnlMsgId" minOccurs="0"/>
 *         &lt;element name="BizCtrlInf" type="{}BizCtrlInf"/>
 *         &lt;element name="QuoteInf" type="{}QuoteInf" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MainBody", propOrder = {
    "msgId",
    "orgnlMsgId",
    "bizCtrlInf",
    "quoteInf"
})
public class MainBody implements Serializable {

    @XmlElement(name = "MsgId", required = true)
    protected MsgId msgId;
    @XmlElement(name = "OrgnlMsgId")
    protected OrgnlMsgId orgnlMsgId;
    @XmlElement(name = "BizCtrlInf", required = true)
    protected BizCtrlInf bizCtrlInf;
    @XmlElement(name = "QuoteInf")
    protected QuoteInf quoteInf;

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link MsgId }
     *     
     */
    public MsgId getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgId }
     *     
     */
    public void setMsgId(MsgId value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the orgnlMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link OrgnlMsgId }
     *     
     */
    public OrgnlMsgId getOrgnlMsgId() {
        return orgnlMsgId;
    }

    /**
     * Sets the value of the orgnlMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgnlMsgId }
     *     
     */
    public void setOrgnlMsgId(OrgnlMsgId value) {
        this.orgnlMsgId = value;
    }

    /**
     * Gets the value of the bizCtrlInf property.
     * 
     * @return
     *     possible object is
     *     {@link BizCtrlInf }
     *     
     */
    public BizCtrlInf getBizCtrlInf() {
        return bizCtrlInf;
    }

    /**
     * Sets the value of the bizCtrlInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BizCtrlInf }
     *     
     */
    public void setBizCtrlInf(BizCtrlInf value) {
        this.bizCtrlInf = value;
    }

    /**
     * Gets the value of the quoteInf property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteInf }
     *     
     */
    public QuoteInf getQuoteInf() {
        return quoteInf;
    }

    /**
     * Sets the value of the quoteInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteInf }
     *     
     */
    public void setQuoteInf(QuoteInf value) {
        this.quoteInf = value;
    }

}
