//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:14:23 下午 CST 
//


package share.msg.CAS001Msg;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MsgId"/>
 *         &lt;element ref="{}StlInf"/>
 *         &lt;element ref="{}StlRstInf"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "msgId",
    "stlInf",
    "stlRstInf"
})
@XmlRootElement(name = "MainBody")
public class MainBody implements Serializable {

    @XmlElement(name = "MsgId", required = true)
    protected MsgId msgId;
    @XmlElement(name = "StlInf", required = true)
    protected StlInf stlInf;
    @XmlElement(name = "StlRstInf", required = true)
    protected StlRstInf stlRstInf;

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link MsgId }
     *     
     */
    public MsgId getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgId }
     *     
     */
    public void setMsgId(MsgId value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the stlInf property.
     * 
     * @return
     *     possible object is
     *     {@link StlInf }
     *     
     */
    public StlInf getStlInf() {
        return stlInf;
    }

    /**
     * Sets the value of the stlInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link StlInf }
     *     
     */
    public void setStlInf(StlInf value) {
        this.stlInf = value;
    }

    /**
     * Gets the value of the stlRstInf property.
     * 
     * @return
     *     possible object is
     *     {@link StlRstInf }
     *     
     */
    public StlRstInf getStlRstInf() {
        return stlRstInf;
    }

    /**
     * Sets the value of the stlRstInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link StlRstInf }
     *     
     */
    public void setStlRstInf(StlRstInf value) {
        this.stlRstInf = value;
    }

}
