//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:14:23 下午 CST 
//


package share.msg.CAS001Msg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.river.practice.msg.CAS001Msg package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StlTp_QNAME = new QName("", "StlTp");
    private final static QName _StlFailRsn_QNAME = new QName("", "StlFailRsn");
    private final static QName _SetMode_QNAME = new QName("", "SetMode");
    private final static QName _ClrTp_QNAME = new QName("", "ClrTp");
    private final static QName _StlRlt_QNAME = new QName("", "StlRlt");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.river.practice.msg.CAS001Msg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link PayInf }
     * 
     */
    public PayInf createPayInf() {
        return new PayInf();
    }

    /**
     * Create an instance of {@link RcvInf }
     * 
     */
    public RcvInf createRcvInf() {
        return new RcvInf();
    }

    /**
     * Create an instance of {@link StlInf }
     * 
     */
    public StlInf createStlInf() {
        return new StlInf();
    }

    /**
     * Create an instance of {@link StlRstInf }
     * 
     */
    public StlRstInf createStlRstInf() {
        return new StlRstInf();
    }

    /**
     * Create an instance of {@link CurrencyAndAmount }
     * 
     */
    public CurrencyAndAmount createCurrencyAndAmount() {
        return new CurrencyAndAmount();
    }

    /**
     * Create an instance of {@link MainBody }
     * 
     */
    public MainBody createMainBody() {
        return new MainBody();
    }

    /**
     * Create an instance of {@link MsgId }
     * 
     */
    public MsgId createMsgId() {
        return new MsgId();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StlTp")
    public JAXBElement<String> createStlTp(String value) {
        return new JAXBElement<String>(_StlTp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StlFailRsn")
    public JAXBElement<String> createStlFailRsn(String value) {
        return new JAXBElement<String>(_StlFailRsn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SetMode")
    public JAXBElement<String> createSetMode(String value) {
        return new JAXBElement<String>(_SetMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ClrTp")
    public JAXBElement<String> createClrTp(String value) {
        return new JAXBElement<String>(_ClrTp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StlRlt")
    public JAXBElement<String> createStlRlt(String value) {
        return new JAXBElement<String>(_StlRlt_QNAME, String.class, null, value);
    }

}
