//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:14:23 下午 CST 
//


package share.msg.CAS001Msg;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BrId" type="{}MaxMin9NumericText"/>
 *         &lt;element name="TAcctNo" type="{}Max32AlphaNumericText"/>
 *         &lt;element name="TAcctNm" type="{}Max150Text"/>
 *         &lt;element name="FAcctNo" type="{}Max32AlphaNumericText" minOccurs="0"/>
 *         &lt;element name="FAcctNm" type="{}Max150Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "brId",
    "tAcctNo",
    "tAcctNm",
    "fAcctNo",
    "fAcctNm"
})
@XmlRootElement(name = "PayInf")
public class PayInf implements Serializable {

    @XmlElement(name = "BrId", required = true)
    protected String brId;
    @XmlElement(name = "TAcctNo", required = true)
    protected String tAcctNo;
    @XmlElement(name = "TAcctNm", required = true)
    protected String tAcctNm;
    @XmlElement(name = "FAcctNo")
    protected String fAcctNo;
    @XmlElement(name = "FAcctNm")
    protected String fAcctNm;

    /**
     * Gets the value of the brId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrId() {
        return brId;
    }

    /**
     * Sets the value of the brId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrId(String value) {
        this.brId = value;
    }

    /**
     * Gets the value of the tAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAcctNo() {
        return tAcctNo;
    }

    /**
     * Sets the value of the tAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAcctNo(String value) {
        this.tAcctNo = value;
    }

    /**
     * Gets the value of the tAcctNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAcctNm() {
        return tAcctNm;
    }

    /**
     * Sets the value of the tAcctNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAcctNm(String value) {
        this.tAcctNm = value;
    }

    /**
     * Gets the value of the fAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAcctNo() {
        return fAcctNo;
    }

    /**
     * Sets the value of the fAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAcctNo(String value) {
        this.fAcctNo = value;
    }

    /**
     * Gets the value of the fAcctNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAcctNm() {
        return fAcctNm;
    }

    /**
     * Sets the value of the fAcctNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAcctNm(String value) {
        this.fAcctNm = value;
    }

}
