//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package share.msg.CES003Msg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;


/**
 * <p>Java class for DealInf complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DealInf">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DealId" type="{}Max20AlphaNumericText"/>
 *         &lt;element name="TrdType" type="{}TrdType"/>
 *         &lt;element name="TrdDate" type="{}ISODate"/>
 *         &lt;element name="DealTime" type="{}ISODateTime"/>
 *         &lt;element name="DealSta" type="{}DealSta"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DealInf", propOrder = {
    "dealId",
    "trdType",
    "trdDate",
    "dealTime",
    "dealSta"
})
public class DealInf implements Serializable {

    @XmlElement(name = "DealId", required = true)
    protected String dealId;
    @XmlElement(name = "TrdType", required = true)
    protected TrdType trdType;
    @XmlElement(name = "TrdDate", required = true)
    protected XMLGregorianCalendar trdDate;
    @XmlElement(name = "DealTime", required = true)
    protected XMLGregorianCalendar dealTime;
    @XmlElement(name = "DealSta", required = true)
    protected DealSta dealSta;

    /**
     * Gets the value of the dealId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealId() {
        return dealId;
    }

    /**
     * Sets the value of the dealId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealId(String value) {
        this.dealId = value;
    }

    /**
     * Gets the value of the trdType property.
     * 
     * @return
     *     possible object is
     *     {@link TrdType }
     *     
     */
    public TrdType getTrdType() {
        return trdType;
    }

    /**
     * Sets the value of the trdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrdType }
     *     
     */
    public void setTrdType(TrdType value) {
        this.trdType = value;
    }

    /**
     * Gets the value of the trdDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrdDate() {
        return trdDate;
    }

    /**
     * Sets the value of the trdDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrdDate(XMLGregorianCalendar value) {
        this.trdDate = value;
    }

    /**
     * Gets the value of the dealTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDealTime() {
        return dealTime;
    }

    /**
     * Sets the value of the dealTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDealTime(XMLGregorianCalendar value) {
        this.dealTime = value;
    }

    /**
     * Gets the value of the dealSta property.
     * 
     * @return
     *     possible object is
     *     {@link DealSta }
     *     
     */
    public DealSta getDealSta() {
        return dealSta;
    }

    /**
     * Sets the value of the dealSta property.
     * 
     * @param value
     *     allowed object is
     *     {@link DealSta }
     *     
     */
    public void setDealSta(DealSta value) {
        this.dealSta = value;
    }

}
