//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package share.msg.CES002Msg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.io.Serializable;


/**
 * <p>Java class for Bill complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bill">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CdNo" type="{}Max30NumericText"/>
 *         &lt;element name="CdAmt" type="{}CurrencyAndAmount"/>
 *         &lt;element name="DueDt" type="{}ISODate"/>
 *         &lt;element name="MatDt" type="{}ISODate"/>
 *         &lt;element name="DsctDt" type="{}ISODate"/>
 *         &lt;element name="IssDt" type="{}ISODate"/>
 *         &lt;element name="DwrName" type="{}Max60Text"/>
 *         &lt;element name="PayName" type="{}Max60Text"/>
 *         &lt;element name="AcptSvcrBrId" type="{}MaxMin9NumericText"/>
 *         &lt;element name="DsctBrId" type="{}MaxMin9NumericText"/>
 *         &lt;element name="AddGrntBrId" type="{}MaxMin9NumericText" minOccurs="0"/>
 *         &lt;element name="AcptCfmBrId" type="{}MaxMin9NumericText" minOccurs="0"/>
 *         &lt;element name="AcptGrntBrId" type="{}MaxMin9NumericText" minOccurs="0"/>
 *         &lt;element name="DsctGrntBrId" type="{}MaxMin9NumericText" minOccurs="0"/>
 *         &lt;element name="TenorDays" type="{}Max10NumericText"/>
 *         &lt;element name="PayInt" type="{}CurrencyAndAmount"/>
 *         &lt;element name="SetAmt" type="{}CurrencyAndAmount"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bill", propOrder = {
    "cdNo",
    "cdAmt",
    "dueDt",
    "matDt",
    "dsctDt",
    "issDt",
    "dwrName",
    "payName",
    "acptSvcrBrId",
    "dsctBrId",
    "addGrntBrId",
    "acptCfmBrId",
    "acptGrntBrId",
    "dsctGrntBrId",
    "tenorDays",
    "payInt",
    "setAmt"
})
public class Bill implements Serializable {

    @XmlElement(name = "CdNo", required = true)
    protected String cdNo;
    @XmlElement(name = "CdAmt", required = true)
    protected CurrencyAndAmount cdAmt;
    @XmlElement(name = "DueDt", required = true)
    protected XMLGregorianCalendar dueDt;
    @XmlElement(name = "MatDt", required = true)
    protected XMLGregorianCalendar matDt;
    @XmlElement(name = "DsctDt", required = true)
    protected XMLGregorianCalendar dsctDt;
    @XmlElement(name = "IssDt", required = true)
    protected XMLGregorianCalendar issDt;
    @XmlElement(name = "DwrName", required = true)
    protected String dwrName;
    @XmlElement(name = "PayName", required = true)
    protected String payName;
    @XmlElement(name = "AcptSvcrBrId", required = true)
    protected String acptSvcrBrId;
    @XmlElement(name = "DsctBrId", required = true)
    protected String dsctBrId;
    @XmlElement(name = "AddGrntBrId")
    protected String addGrntBrId;
    @XmlElement(name = "AcptCfmBrId")
    protected String acptCfmBrId;
    @XmlElement(name = "AcptGrntBrId")
    protected String acptGrntBrId;
    @XmlElement(name = "DsctGrntBrId")
    protected String dsctGrntBrId;
    @XmlElement(name = "TenorDays", required = true)
    protected String tenorDays;
    @XmlElement(name = "PayInt", required = true)
    protected CurrencyAndAmount payInt;
    @XmlElement(name = "SetAmt", required = true)
    protected CurrencyAndAmount setAmt;

    /**
     * Gets the value of the cdNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdNo() {
        return cdNo;
    }

    /**
     * Sets the value of the cdNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdNo(String value) {
        this.cdNo = value;
    }

    /**
     * Gets the value of the cdAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAndAmount }
     *     
     */
    public CurrencyAndAmount getCdAmt() {
        return cdAmt;
    }

    /**
     * Sets the value of the cdAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAndAmount }
     *     
     */
    public void setCdAmt(CurrencyAndAmount value) {
        this.cdAmt = value;
    }

    /**
     * Gets the value of the dueDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDt() {
        return dueDt;
    }

    /**
     * Sets the value of the dueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDt(XMLGregorianCalendar value) {
        this.dueDt = value;
    }

    /**
     * Gets the value of the matDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMatDt() {
        return matDt;
    }

    /**
     * Sets the value of the matDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMatDt(XMLGregorianCalendar value) {
        this.matDt = value;
    }

    /**
     * Gets the value of the dsctDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDsctDt() {
        return dsctDt;
    }

    /**
     * Sets the value of the dsctDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDsctDt(XMLGregorianCalendar value) {
        this.dsctDt = value;
    }

    /**
     * Gets the value of the issDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssDt() {
        return issDt;
    }

    /**
     * Sets the value of the issDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssDt(XMLGregorianCalendar value) {
        this.issDt = value;
    }

    /**
     * Gets the value of the dwrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDwrName() {
        return dwrName;
    }

    /**
     * Sets the value of the dwrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDwrName(String value) {
        this.dwrName = value;
    }

    /**
     * Gets the value of the payName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayName() {
        return payName;
    }

    /**
     * Sets the value of the payName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayName(String value) {
        this.payName = value;
    }

    /**
     * Gets the value of the acptSvcrBrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcptSvcrBrId() {
        return acptSvcrBrId;
    }

    /**
     * Sets the value of the acptSvcrBrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcptSvcrBrId(String value) {
        this.acptSvcrBrId = value;
    }

    /**
     * Gets the value of the dsctBrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsctBrId() {
        return dsctBrId;
    }

    /**
     * Sets the value of the dsctBrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsctBrId(String value) {
        this.dsctBrId = value;
    }

    /**
     * Gets the value of the addGrntBrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddGrntBrId() {
        return addGrntBrId;
    }

    /**
     * Sets the value of the addGrntBrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddGrntBrId(String value) {
        this.addGrntBrId = value;
    }

    /**
     * Gets the value of the acptCfmBrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcptCfmBrId() {
        return acptCfmBrId;
    }

    /**
     * Sets the value of the acptCfmBrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcptCfmBrId(String value) {
        this.acptCfmBrId = value;
    }

    /**
     * Gets the value of the acptGrntBrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcptGrntBrId() {
        return acptGrntBrId;
    }

    /**
     * Sets the value of the acptGrntBrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcptGrntBrId(String value) {
        this.acptGrntBrId = value;
    }

    /**
     * Gets the value of the dsctGrntBrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsctGrntBrId() {
        return dsctGrntBrId;
    }

    /**
     * Sets the value of the dsctGrntBrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsctGrntBrId(String value) {
        this.dsctGrntBrId = value;
    }

    /**
     * Gets the value of the tenorDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenorDays() {
        return tenorDays;
    }

    /**
     * Sets the value of the tenorDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenorDays(String value) {
        this.tenorDays = value;
    }

    /**
     * Gets the value of the payInt property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAndAmount }
     *     
     */
    public CurrencyAndAmount getPayInt() {
        return payInt;
    }

    /**
     * Sets the value of the payInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAndAmount }
     *     
     */
    public void setPayInt(CurrencyAndAmount value) {
        this.payInt = value;
    }

    /**
     * Gets the value of the setAmt property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAndAmount }
     *     
     */
    public CurrencyAndAmount getSetAmt() {
        return setAmt;
    }

    /**
     * Sets the value of the setAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAndAmount }
     *     
     */
    public void setSetAmt(CurrencyAndAmount value) {
        this.setAmt = value;
    }

}
